### ISSUE TITLE
Authorization error on tracking

### ISSUE THREAD

**Issue by lucasiq** [Jobs-4-You/J4U-WebApp#11]
Issue prevents navigation. In any case, we need to handle it on the front-end so that navigation doesn't fail when tracking stops. Error might have happened when I stopped Python, which might occur in production in case we need to restart it.

`[VM120 main.js:231817 POST http://localhost:5000/track 401 (UNAUTHORIZED)
dispatchXhrRequest @ VM120 main.js:231817
xhrAdapter @ VM120 main.js:231651
dispatchRequest @ VM120 main.js:232256
Promise.then (async)
request @ VM120 main.js:232063
wrap @ VM120 main.js:232516
trackQuery @ VM120 main.js:305448
logPageView @ VM120 main.js:305557
(anonymous) @ VM120 main.js:305527
listener @ VM120 main.js:239215
(anonymous) @ VM120 main.js:239234
notifyListeners @ VM120 main.js:239233
setState @ VM120 main.js:238760
(anonymous) @ VM120 main.js:238868
confirmTransitionTo @ VM120 main.js:239205
push @ VM120 main.js:238848
errorResponseHandler @ VM120 main.js:305350
Promise.then (async)
request @ VM120 main.js:232063
wrap @ VM120 main.js:232516
trackQuery @ VM120 main.js:305448
logPageView @ VM120 main.js:305557
(anonymous) @ VM120 main.js:305527
listener @ VM120 main.js:239215
(anonymous) @ VM120 main.js:239234
notifyListeners @ VM120 main.js:239233
setState @ VM120 main.js:238760
(anonymous) @ VM120 main.js:238868
confirmTransitionTo @ VM120 main.js:239205
push @ VM120 main.js:238848
onClick @ VM120 main.js:301012
callCallback @ VM120 main.js:250368
invokeGuardedCallbackDev @ VM120 main.js:250418
invokeGuardedCallback @ VM120 main.js:250471
invokeGuardedCallbackAndCatchFirstError @ VM120 main.js:250485
executeDispatch @ VM120 main.js:250816
executeDispatchesInOrder @ VM120 main.js:250835
executeDispatchesAndRelease @ VM120 main.js:250936
executeDispatchesAndReleaseTopLevel @ VM120 main.js:250947
forEachAccumulated @ VM120 main.js:250917
runEventsInBatch @ VM120 main.js:251078
runExtractedEventsInBatch @ VM120 main.js:251087
handleTopLevel @ VM120 main.js:255080
batchedUpdates$1 @ VM120 main.js:267720
batchedUpdates @ VM120 main.js:252412
dispatchEvent @ VM120 main.js:255159
interactiveUpdates$1 @ VM120 main.js:267775
interactiveUpdates @ VM120 main.js:252431
dispatchInteractiveEvent @ VM120 main.js:255136
VM120 main.js:305347 Error: Request failed with status code 401
    at createError (VM120 main.js:232183)
    at settle (VM120 main.js:232346)
    at XMLHttpRequest.handleLoad (VM120 main.js:231716)
VM120 main.js:239346 Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack
warning @ VM120 main.js:239346
(anonymous) @ VM120 main.js:238870
confirmTransitionTo @ VM120 main.js:239205
push @ VM120 main.js:238848
errorResponseHandler @ VM120 main.js:305350
Promise.then (async)
request @ VM120 main.js:232063
wrap @ VM120 main.js:232516
trackQuery @ VM120 main.js:305448
logPageView @ VM120 main.js:305557
(anonymous) @ VM120 main.js:305527
listener @ VM120 main.js:239215
(anonymous) @ VM120 main.js:239234
notifyListeners @ VM120 main.js:239233
setState @ VM120 main.js:238760
(anonymous) @ VM120 main.js:238868
confirmTransitionTo @ VM120 main.js:239205
push @ VM120 main.js:238848
errorResponseHandler @ VM120 main.js:305350
Promise.then (async)
request @ VM120 main.js:232063
wrap @ VM120 main.js:232516
trackQuery @ VM120 main.js:305448
logPageView @ VM120 main.js:305557
(anonymous) @ VM120 main.js:305527
listener @ VM120 main.js:239215
(anonymous) @ VM120 main.js:239234
notifyListeners @ VM120 main.js:239233
setState @ VM120 main.js:238760
(anonymous) @ VM120 main.js:238868
confirmTransitionTo @ VM120 main.js:239205
push @ VM120 main.js:238848
onClick @ VM120 main.js:301012
callCallback @ VM120 main.js:250368
invokeGuardedCallbackDev @ VM120 main.js:250418
invokeGuardedCallback @ VM120 main.js:250471
invokeGuardedCallbackAndCatchFirstError @ VM120 main.js:250485
executeDispatch @ VM120 main.js:250816
executeDispatchesInOrder @ VM120 main.js:250835
executeDispatchesAndRelease @ VM120 main.js:250936
executeDispatchesAndReleaseTopLevel @ VM120 main.js:250947
forEachAccumulated @ VM120 main.js:250917
runEventsInBatch @ VM120 main.js:251078
runExtractedEventsInBatch @ VM120 main.js:251087
handleTopLevel @ VM120 main.js:255080
batchedUpdates$1 @ VM120 main.js:267720
batchedUpdates @ VM120 main.js:252412
dispatchEvent @ VM120 main.js:255159
interactiveUpdates$1 @ VM120 main.js:267775
interactiveUpdates @ VM120 main.js:252431
dispatchInteractiveEvent @ VM120 main.js:255136
VM120 main.js:305526 PUSH /logout undefined](url)`

**Comment by lucasiq** [comment]
Error doesn't occur when using the application on incognito mode or after clearing cache, so I am assuming it might have to do with the localstorage token or with the time tracking feature.

**Comment by Mauro-Cherubini** [comment]
Got the same issue on Chrome trying to log in a few weeks after the last attempt:

POP /signin undefined
:5000/track:1 POST https://j4u.unil.ch:5000/track 401 (UNAUTHORIZED)
VM58 main.js:270 Error: Request failed with status code 401
    at e.exports (VM58 main.js:6)
    at e.exports (VM58 main.js:234)
    at XMLHttpRequest.A.<computed> (VM58 main.js:6)
VM58 main.js:270 PUSH /logout undefined
VM58 main.js:276 aaa
VM58 main.js:6 POST https://j4u.unil.ch:5000/track 401 (UNAUTHORIZED)
(anonymous) @ VM58 main.js:6
e.exports @ VM58 main.js:6
e.exports @ VM58 main.js:234
Promise.then (async)
s.request @ VM58 main.js:234
(anonymous) @ VM58 main.js:6
vt @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
r @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
notifyListeners @ VM58 main.js:270
A @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
confirmTransitionTo @ VM58 main.js:270
push @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
Promise.then (async)
s.request @ VM58 main.js:234
(anonymous) @ VM58 main.js:6
vt @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
r @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
notifyListeners @ VM58 main.js:270
A @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
confirmTransitionTo @ VM58 main.js:270
g @ VM58 main.js:270
m @ VM58 main.js:270
hashchange (async)
(anonymous) @ VM58 main.js:270
(anonymous) @ VM58 main.js:270
confirmTransitionTo @ VM58 main.js:270
push @ VM58 main.js:270
r.handleClick @ VM58 main.js:270
(anonymous) @ VM58 main.js:207
d @ VM58 main.js:207
(anonymous) @ VM58 main.js:207
C @ VM58 main.js:207
N @ VM58 main.js:207
x @ VM58 main.js:207
O @ VM58 main.js:207
Bn @ VM58 main.js:207
Lo @ VM58 main.js:207
Ie @ VM58 main.js:207
Nn @ VM58 main.js:207
Qo @ VM58 main.js:207
Sn @ VM58 main.js:207
VM58 main.js:270 Error: Request failed with status code 401
    at e.exports (VM58 main.js:6)
    at e.exports (VM58 main.js:234)
    at XMLHttpRequest.A.<computed> (VM58 main.js:6)
VM58 main.js:270 PUSH /logout undefined
Navigated to https://j4u.unil.ch/

**Comment by lsrodri** [comment]
Fixed by @jimzer though https://github.com/Jobs-4-You/J4U-WebApp/commit/ff71fe42606fe72bddcedab6c299cd369e12e742
