### ISSUE TITLE
Define final certificate text

### ISSUE THREAD

**Issue by lucasiq** [Jobs-4-You/J4U-WebApp#13]
This is the current state of this certificate:

https://docs.google.com/document/d/1iKpJKsWDqu8iMI0Xi6X-Q44zCyMIN7LpWVyoOyRLgx0/edit?usp=sharing

@hbenghalem we would like to obtain the final text to avoid re-work.

**Comment by hbenghalem** [comment]
Since the certificate won't be part of the tool for cohort 0 I will do it after the baseline sessions. I guess I need to solve the Isco code pb first.

**Comment by lucasiq** [comment]
I just saw your response. In any case, I had sent an email to the team to get their input on it, so hopefully they can work on this definition while you’re dealing with the ISCO codes problem

**Comment by lucasiq** [comment]
Template received by mail

**Comment by hbenghalem** [comment]
Thanks!

Le dim. 23 juin 2019 à 12:31, Lucas Rodrigues <notifications@github.com> a
écrit :
