### ISSUE TITLE
I don't have the tool as it should be

### ISSUE THREAD

**Issue by hbenghalem** [Jobs-4-You/J4U-WebApp#24]
When I connect myself to the tool, I don't get the tool as it should be (I don't have the alpha/beta/ it is written "recherche d'emploi" instead of "recommandations professionnelles".
When I log-in with one of the participants accounts, it is working properly. Did you change the plateform only for cohort 0?
I don't know if it is a "real" issue.
Thanks

**Comment by lucasiq** [comment]
Hi Hélène,

We had defined that any user whose group field does not contain J4U receives the control-group interface. Does it match the features you would expect from a control group user? You can change your group field through the admin interface, log out and in to see if you see the full J4U experience.

**Comment by hbenghalem** [comment]
Oh yes, you are right! I will take a look at it and test it.
Thanks

**Comment by hbenghalem** [comment]
I have look at the not-J4U tool and it looks good to me. Thank you very much!
