### ISSUE TITLE
Pb on j4u.unil.ch/update

### ISSUE THREAD

**Issue by hbenghalem** [Jobs-4-You/J4U-WebApp#26]
Hi 
In the update form:
- Field=FixedOldJobValue --> I have the field "value"
- Field=group--> I have the field "value" = "true" or "false"
Shouldn't it be the opposite?
FixedOldJobValue with "value" true vs false
group with "value" empty
Thanks!

**Comment by lsrodri** [comment]
I have updated the code to fix it. Could you clear cache and check whether it's fixed?

**Comment by hbenghalem** [comment]
Yes it is fixed! thanks a lot!
