### ISSUE TITLE
Create a separate search engine for the control group

### ISSUE THREAD

**Issue by lucasiq** [Jobs-4-You/J4U-WebApp#3]
The control group search should not use the recommendations engine. Instead, it should target SECO's API. We cannot directly access the SECO API as it would cause cross-domain issues, so we need to send requests through a proxy.

**Comment by lucasiq** [comment]
@Mauro-Cherubini can you confirm that the control group will take the survey?

**Comment by Mauro-Cherubini** [comment]
Yes, confirmed as per email thread.
