### ISSUE TITLE
Add a salutation field to user registration

### ISSUE THREAD

**Issue by lucasiq** [Jobs-4-You/J4U-WebApp#5]
Add a salutation field as a string as we need it to generate a certificate with salutation (ex: Mme Poulain)

Update:
- Production Database
- Python DB model
- Validation schema
- Registration form
- Python sign-up validation
- Profile editing form
- Python update validation
- App overall state data props

**Comment by lucasiq** [comment]
Almost finished, but unable to set existing value on load or edit value on `UpdateInfos.js`. @jimzer could you contribute with your React expertise?

**Comment by lucasiq** [comment]
Nevermind, fixed it.

**Comment by lucasiq** [comment]
@hbenghalem I have added the field `civilite` to the production database after cohort 0 registered, so I had to assign salutations based on my assumptions of participants' first names. Could you use the admin tool to check whether the information returned is correct for the participants?

**Comment by hbenghalem** [comment]
The information is correct. Thanks Lucas
