### ISSUE TITLE
Issue with Previous Job Field on the Recommendation page

### ISSUE THREAD

**Issue by lucasiq** [Jobs-4-You/J4U-WebApp#7]
Suggestions are being shown before users type in their profession, so users are assuming those are the only possible options. 

Results should be shown in alphabetical order to make them more relevant to what is being typed by the user

The field should be emptied so once it receives focus as it's behaving inappropriately if it has text and needs to be changed

**Comment by hbenghalem** [comment]
Do you think this could be implemented before the baseline session or it is too late?

**Comment by lucasiq** [comment]
As the 3 issues involve the web app, back-end, and the SECO AVAM database, it's unlikely we can develop it and fully test it in two days. The alternative would be to explain how to get around it during the presentation by logging into the system and showing them how to do it. Since we'll block them from changing this value after the baseline session, the problem won't affect them afterwards.

**Comment by hbenghalem** [comment]
ok we will explain them how to get around small bugs during the session. thanks

**Comment by lucasiq** [comment]
After cohort 0 baseline session, two more fixes:
- each option value / job title should start with uppercase for consistency
- we should increase the number of returned results as some keywords return many results

**Comment by lucasiq** [comment]
Fixed by https://github.com/Jobs-4-You/J4U-WebApp/commit/f85d31e52703cee1ce576759fdfedd482abe72da https://github.com/Jobs-4-You/J4U-WebApp/commit/5a5657219868bcde4ddae40a27c1862e4aa118b3 https://github.com/Jobs-4-You/J4U-WebApp/commit/71e15710f6ae79016d5951de17c95caf7eb39164

**Comment by hbenghalem** [comment]
Thanks!

Le dim. 23 juin 2019 à 12:40, Lucas Rodrigues <notifications@github.com> a
écrit :
